# Generated by Django 5.2.8 on 2025-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
