# Generated by Django 5.2.8 on 2025-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='devuelto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='activa',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('prestado', 'Prestado'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado')], default='prestado', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplida', 'Cumplida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
